### ISSUE TITLE
Register

### ISSUE THREAD

**Issue by paulflang** [SciML/SBMLToolkitTestSuite.jl#8]

**Comment by paulflang** [comment]
@JuliaRegistrator register()

**Comment by paulflang** [comment]
@JuliaRegistrator register()

**Comment by paulflang** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register

Release notes:

## Breaking changes

Support for MTK v11 Catalyst v16

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()
